import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import { WalletContextProvider } from "@/providers/walletContextProvider";
import QueryClientProvider from "@/providers/queryClient";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <WalletContextProvider>
      <html
        lang="en"
        className={`${geist.variable}`}
        suppressHydrationWarning={true}
      >
        <body>
          <QueryClientProvider>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </QueryClientProvider>
        </body>
      </html>
    </WalletContextProvider>
  );
}
